CREATE TABLE `customer_addresses` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`type` text NOT NULL,
	`label` text,
	`is_default` integer DEFAULT false,
	`recipient_name` text NOT NULL,
	`recipient_phone` text NOT NULL,
	`city` text NOT NULL,
	`district` text NOT NULL,
	`postal_code` text NOT NULL,
	`street` text NOT NULL,
	`building` text,
	`floor` text,
	`room` text,
	`delivery_instructions` text,
	`access_code` text,
	`last_used_at` integer,
	`usage_count` integer DEFAULT 0,
	`is_active` integer DEFAULT true,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `customer_notification_preferences` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`email_order_updates` integer DEFAULT true,
	`email_appointment_reminders` integer DEFAULT true,
	`email_newsletters` integer DEFAULT true,
	`email_promotions` integer DEFAULT true,
	`email_price_alerts` integer DEFAULT true,
	`email_product_recommendations` integer DEFAULT false,
	`sms_order_updates` integer DEFAULT false,
	`sms_appointment_reminders` integer DEFAULT true,
	`sms_promotions` integer DEFAULT false,
	`sms_delivery_updates` integer DEFAULT true,
	`push_order_updates` integer DEFAULT true,
	`push_appointment_reminders` integer DEFAULT true,
	`push_promotions` integer DEFAULT false,
	`email_frequency` text DEFAULT 'immediate',
	`sms_frequency` text DEFAULT 'important_only',
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `customer_payment_methods` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`type` text NOT NULL,
	`provider` text,
	`card_token` text,
	`last_four_digits` text,
	`expiry_month` text,
	`expiry_year` text,
	`cardholder_name` text,
	`bank_name` text,
	`bank_code` text,
	`account_type` text,
	`account_last_four` text,
	`wallet_provider` text,
	`wallet_account_id` text,
	`is_default` integer DEFAULT false,
	`is_active` integer DEFAULT true,
	`nickname` text,
	`encryption_key_id` text,
	`last_used_at` integer,
	`usage_count` integer DEFAULT 0,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `customer_recently_viewed` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`product_id` text NOT NULL,
	`viewed_at` integer,
	`view_duration_seconds` integer,
	`referrer_url` text,
	`device_type` text,
	`created_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `customer_reviews` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`product_id` text NOT NULL,
	`order_id` text,
	`rating` integer NOT NULL,
	`title` text NOT NULL,
	`content` text NOT NULL,
	`pros` text DEFAULT '[]',
	`cons` text DEFAULT '[]',
	`images` text DEFAULT '[]',
	`status` text DEFAULT 'pending',
	`moderated_by` text,
	`moderated_at` integer,
	`moderation_notes` text,
	`helpful_count` integer DEFAULT 0,
	`total_votes` integer DEFAULT 0,
	`verified` integer DEFAULT false,
	`purchase_date` integer,
	`featured` integer DEFAULT false,
	`display_name` text,
	`show_full_name` integer DEFAULT false,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`order_id`) REFERENCES `orders`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `customer_wishlists` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`product_id` text NOT NULL,
	`variant_id` text,
	`notes` text,
	`priority` text DEFAULT 'medium',
	`price_alert` real,
	`added_at` integer,
	`last_viewed_at` integer,
	`view_count` integer DEFAULT 1,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `user_security` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`password_hash` text,
	`password_salt` text,
	`password_last_changed` integer,
	`force_password_change` integer DEFAULT false,
	`last_login_at` integer,
	`last_login_ip` text,
	`last_login_user_agent` text,
	`login_count` integer DEFAULT 0,
	`two_factor_enabled` integer DEFAULT false,
	`two_factor_secret` text,
	`backup_codes` text DEFAULT '[]',
	`is_locked` integer DEFAULT false,
	`locked_at` integer,
	`locked_reason` text,
	`failed_login_attempts` integer DEFAULT 0,
	`last_failed_login_at` integer,
	`allow_data_collection` integer DEFAULT true,
	`allow_marketing` integer DEFAULT true,
	`allow_sms_marketing` integer DEFAULT false,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
